site_name: PaintByChar
site_description: Convert ASCII grids into colorful images with Python.
site_url: https://jgd10.github.io/PaintByChar/
repo_url: https://github.com/jgd10/PaintByChar
repo_name: jgd10/PaintByChar

nav:
  - Home: index.md
  - API: api.md
  - Examples: examples.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jgd10/PaintByChar
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/PaintByChar/

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
