[metadata]
name = paintbychar
version = 0.1.0
description = Character-block image generator
long_description = file: README.md
long_description_content_type = text/markdown
author = James Derrick
author_email = jgd10.github@gmail.com
url = https://github.com/jgd10/PaintByChar
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
py_modules =
    main
    paintbychar
package_dir =
    = src
install_requires =
    pillow
    matplotlib
python_requires = >=3.12